name: react project
on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout action
        uses: actions/checkout@v3

      - name: cache actions
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-dep-${{ hashFiles('**/package-lock.json') }}  # Fixed incorrect file name

      - name: build
        run: |
          npm install
          npm run build

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: checkout action
        uses: actions/checkout@v3

      - name: cache actions
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-dep-${{ hashFiles('**/package-lock.json') }}  # Fixed incorrect file name

      - name: build
        run: |
          npm install
          npm run build
