name: event-trigger
on:
    pul_request:
        types:
            - opened 
            workflow_dispatch:
                jobs:
                    activity:
                        runs-on: ubuntu-latest
                        steps:
                            -n name: print data
                            run: echo " working"