name: event-trigger
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:  # Fix: Properly aligned outside of pull_request

jobs:
  activity:
    runs-on: ubuntu-latest
    steps:
      - name: Print data  # Fix: Correct key format
        run: echo "Working"
