name: filtering
on:
  push:
    branches:
      - main
      - "master-*"  # Matches branches starting with "master-"
      - "vite/**"    # Matches all branches under "vite/"
    paths:
      - ".github/workflows/*"  # Triggers only if files in this path change

jobs:
  filter:  # Fix: Corrected indentation
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Context
        run: echo "${{ toJson(github.event) }}"  # Fixed function syntax
