name: filtering
on:
    push:
        branches:
            - main
            - 'master-*'
            - 'vite/**'
            paths:
                - 'abc'
                jobs:
                    filter:
                        runs-on: ubuntu-latest
                        steps:
                            - name: github context  
                            run: echo "${{toJson(github.event)}}"