name: multi job
on: [push, workflow_dispatch]

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print first job
        run: echo "Print first job"

  second-job:
    needs: first-job  # Fix: Specify dependency
    runs-on: ubuntu-latest
    steps:
      - name: Print second job
        run: echo "Print second job"
