name: multi job
on: [push, workflow_dispatch]

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print first job
        run: echo "Print first job"

  second-job:
    needs: first-job  # Specifies dependency
    runs-on: ubuntu-latest
    steps:
      - name: Print second job
        run: echo "Print second job"

  third-job:
    needs: second-job  # Specifies dependency
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub Context
        run: echo "${{ toJson(github) }}"
